
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

package compilador_lenguajejava;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WHILE = 7;
  public static final int PUNTO = 12;
  public static final int PUBLIC = 2;
  public static final int TRUE = 11;
  public static final int BOOLEAN = 9;
  public static final int THEN = 6;
  public static final int EOF = 0;
  public static final int IF = 4;
  public static final int FALSE = 10;
  public static final int ELSE = 5;
  public static final int error = 1;
  public static final int PRINT = 8;
  public static final int PRIVATE = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PUBLIC",
  "PRIVATE",
  "IF",
  "ELSE",
  "THEN",
  "WHILE",
  "PRINT",
  "BOOLEAN",
  "FALSE",
  "TRUE",
  "PUNTO"
  };
}

